create extension if not exists pgcrypto;
create table if not exists public.game_sessions (
  id uuid primary key default gen_random_uuid(), public_id uuid not null unique, archive_code text not null,
  status text not null default 'active' check (status in ('active','sealed','expired')),
  player_count smallint not null default 1 check (player_count between 1 and 3), phase text not null,
  identities jsonb not null default '[]'::jsonb, private_state jsonb not null, source_archive_id uuid,
  created_at timestamptz not null default now(), expires_at timestamptz not null default (now() + interval '24 hours'), sealed_at timestamptz
);
create table if not exists public.contributions (
  id uuid primary key default gen_random_uuid(), session_public_id uuid not null references public.game_sessions(public_id) on delete cascade,
  phase text not null, contribution_type text not null check (contribution_type in ('sentence','choice','system_record')),
  content text not null check (char_length(content) <= 500), display_identity text not null,
  source_class text not null default 'registered' check (source_class in ('registered','archive','administrator','unverified')),
  motifs jsonb not null default '[]'::jsonb, is_sealed boolean not null default false, created_at timestamptz not null default now()
);
create table if not exists public.archives (
  id uuid primary key default gen_random_uuid(), session_public_id uuid references public.game_sessions(public_id) on delete set null,
  archive_code text not null, title text not null, final_archive jsonb not null, share_slug text not null unique,
  reuse_allowed boolean not null default true, created_at timestamptz not null default now()
);
alter table public.game_sessions drop constraint if exists game_sessions_source_archive_id_fkey;
alter table public.game_sessions add constraint game_sessions_source_archive_id_fkey foreign key (source_archive_id) references public.archives(id) on delete set null;
create table if not exists public.legacy_fragments (
  id uuid primary key default gen_random_uuid(), archive_id uuid references public.archives(id) on delete cascade,
  quote text not null check (char_length(quote) between 1 and 500), motifs jsonb not null default '[]'::jsonb,
  next_hook text not null, reuse_count integer not null default 0,
  safety_status text not null default 'pending' check (safety_status in ('pending','approved','blocked')),
  created_at timestamptz not null default now()
);
create table if not exists public.rate_limit_events (
  id bigint generated by default as identity primary key, client_key text not null, scope text not null, created_at timestamptz not null default now()
);
create index if not exists game_sessions_public_id_idx on public.game_sessions(public_id);
create index if not exists game_sessions_status_created_idx on public.game_sessions(status, created_at desc);
create index if not exists contributions_session_created_idx on public.contributions(session_public_id, created_at);
create index if not exists archives_share_slug_idx on public.archives(share_slug);
create index if not exists legacy_fragments_reuse_idx on public.legacy_fragments(safety_status, reuse_count, created_at);
create index if not exists rate_limit_lookup_idx on public.rate_limit_events(client_key, scope, created_at desc);
alter table public.game_sessions enable row level security;
alter table public.contributions enable row level security;
alter table public.archives enable row level security;
alter table public.legacy_fragments enable row level security;
alter table public.rate_limit_events enable row level security;
drop policy if exists "public read archives" on public.archives;
create policy "public read archives" on public.archives for select to anon, authenticated using (true);
drop policy if exists "public read approved legacy" on public.legacy_fragments;
create policy "public read approved legacy" on public.legacy_fragments for select to anon, authenticated using (safety_status = 'approved');
